### ISSUE TITLE
Hảo coder :'D

### ISSUE THREAD

**Issue by mocmeo-ship-it** [ndbiaw/cc-ddos#3]
T chạy cái start.bat mà lỗi 3 dòng z :'D

**Comment by ndbiaw** [comment]
Ngu l nên thế.
Tạo issue mà không post debug lên thì bố bạn cũng chả biết lỗi gì :D

**Comment by mocmeo-ship-it** [comment]
Ừ t ngu thật mà
Thế làm kiểu gì :'D

**Comment by ndbiaw** [comment]
> Ừ t ngu thật mà Thế làm kiểu gì :'D

địt mẹ mày post cái log lên, xàm xàm như thằng thiểu năng
đéo post được cái log thì close issue

**Comment by ndbiaw** [comment]
đã tạo acc github thì học cách dùng hộ cái, coi github là google à mà hỏi ngu đéo chịu
sao không hỏi bao giờ giàu hay bao giờ chết cho dễ
